pipeline {
    tools {
        maven 'mvn'
    }
    agent any
    stages {
        stage('Build') {
            dir('jenkins/MyLAB/simple-java-maven-app') {
                steps {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            dir('jenkins/MyLAB/simple-java-maven-app') {
                steps {
                    sh 'mvn test'
                }
                post {
                    always {
                        junit 'target/surefire-reports/*.xml'
                    }
                }
            }
        }
        stage('Deliver') {
            dir('jenkins/MyLAB/simple-java-maven-app') {
                steps {
                    sh './jenkins/scripts/deliver.sh'
                }
            }
        }
    }
}
