pipeline {
    tools {
        maven 'mvn'
    }
    agent any
    stages {
        stage('Build') {
            steps {
                dir('jenkins/MyLAB/simple-java-maven-app') {
                    sh 'mvn -B -DskipTests clean package'
                }
            }
        }
        stage('Test') {
            steps {
                dir('jenkins/MyLAB/simple-java-maven-app') {
                    sh 'mvn test'
                }
            }
            post {
                always {
                    junit 'jenkins/MyLAB/simple-java-maven-app/target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                dir('jenkins/MyLAB/simple-java-maven-app') {
                    sh './jenkins/scripts/deliver.sh'
                }
            }
        }
    }
}
